# Generated by Django 6.0.4 on 2026-05-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventcomment_reply_to_alter_event_max_participants'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventparticipant',
            name='events_eventparticipant_unique_event_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
